site_name: My Docs

theme:
  name: material
  palette:
    primary: green
  features:
    - navigation.tabs
    - navigation.section
    - navigatin.top
    # - toc.integrate

plugins:
  - search:
      lang: ja

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify_cased
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      # linenums: true
      linenums_style: pymdownx-inline

nav:
  - Home: index.md
  - MkDocs:
    - ./mkdocs-point.md 
    - ./codeblock.md
    - ./drawio-with-vscode.md

extra:
  version:
    provider: mike